version: '3.6'

services:
    snowsword:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: SnowSword
        depends_on:
            - snowsword_db
        links:
            - snowsword_db
        ports: 
            - 8081:8081
            - 5005:5005
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mysql://snowsword_db:3306/snowsword?allowPublicKeyRetrieval=true&useSSL=false",
                "spring.datasource.username" : "root",
                "spring.datasource.password" : "root",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
            }'
        entrypoint: ["/root/wait-for-it.sh","SnowSwordDB:3306","--",
                    "java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005","-jar","/root/snowsword-0.0.1-SNAPSHOT.jar",
                    "--server.port=8081"]
                    # "--spring.datasource.url=jdbc:mysql://SnowSwordDB:3306/snowsword",
                    # "--spring.datasource.username=root",
                    # "spring.datasource.password=root"]

    snowsword_db:
        image: mysql:8.0.33
        container_name: SnowSwordDB
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=snowsword


